# Generated by Django 3.2.5 on 2021-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=50)),
                ('book_year', models.IntegerField(max_length=25)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
