# Generated by Django 3.2.5 on 2021-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_lang',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(),
        ),
    ]
